defaults:
  - _self_

audio:
  transformer:
    num_hidden_layers: 14
    num_attention_heads: 8
    intermediate_size: 1024  # MLP dim

vision:
  transformer:
    num_hidden_layers: 14
    num_attention_heads: 8
    intermediate_size: 1024  # MLP dim
  
monitor:
  metric: "val/acc_5_max"
  mode: "max"