defaults:
  - _self_

monitor:
  metric: "val/auroc_macro_epoch"
  mode: "max"

vision:
  vit: 
    dropout: 0.1
    vit: "vit_b_16"

sequential:
  transformer:
    num_hidden_layers: 6
    num_attention_heads: 16
    intermediate_size: 512
    dropout: 0.1