defaults:
  - _self_

audio:
  transformer:
    num_hidden_layers: 14
    num_attention_heads: 8
    intermediate_size: 1024  # MLP dim
    dropout: 0.0

vision:
  transformer:
    num_hidden_layers: 14
    num_attention_heads: 8
    intermediate_size: 1024  # MLP dim
    dropout: 0.0
  
monitor:
  metric: "val/acc_7_max"
  mode: "max"