hidden_dims: [512, 256, 128]
hidden_dropouts: [0.2, 0.2, 0.2]

# Feature counts in the tabular_data tensors emitted by UDM.
input_dims:
  nmr: 249
  ehr: 3584
  olink: 1463
  prs: 135
  bloodbio: 30
  baselinechars: 28
  localenvironment: 33
  arterialstiffness: 9
  anthropometry: 43
  bloodpressure: 12
  ecgduringexercise: 355
  eyemeasures: 310
  bonedensitometry: 27
  handgripstrength: 2
  spirometry: 29
  touchscreen: 119
  cognitivefunction: 27
  hearingtest: 68
  verbalinterview: 224
  bloodcount: 31
  urineassays: 4
  telomeres: 4
  infectiousdiseases: 66
