defaults:
  - plugins: default
  - _self_

splits: /sc-projects/sc-proj-ukb-cvd/data/3_datasets_post/230216_metabolomics/splits_0.yaml
train_split: train
valid_split: valid
test_split: test
combine_eids_as: union
num_workers: 8
batch_size: 512
pin_memory: true
drop_last: true
shuffle: true
keyerr: true
