defaults:
 - plugins: default
 - _self_

splits: /sc-projects/sc-proj-ukb-cvd/data/3_datasets_post/230216_metabolomics/splits_0.yaml
#splits: /sc-projects/sc-proj-ukb-cvd/results/projects/22_multimodal/data/240328/splits_51157/split_0.yaml
train_split: 'train'
valid_split: 'valid'
test_split: 'test'
combine_eids_as: 'union'  # 'intersect'  
num_workers: 8  # 32
batch_size: 512  # 3072  # 512
pin_memory: true
drop_last: true
shuffle: true
keyerr: true  # true if intersect, false if union