defaults:
  - _self_
  - modelname: transformer
  - encoders: ch_sims

dataset: ch_sims  # mimic_symile / mimic_haim / mosi / mosei / ch_sims / ch_sims_v2 / vision_touch / crema_d / vgg_sound / kinetics_400 / kinetics_600 / kinetics_700
split_nr: 1
missing:  # e.g. 2 modalities -> 1 list entry -> defines the percentage of one modality missing
  missing_train: [0.0, 0.0]
  missing_valid: [0.0, 0.0]
  missing_test: [0.0, 0.0]

batch_size: 16

seed: 420
num_workers: 8
precision: "32"
max_epochs: 200
wandb:
  project: "simple_mml_baseline"
  group: None