modelname: aug

optimizer:
  name: schedulefree_sgd  # adamw
  lr: 0.052858427909375304
  warmup_steps: 1000
  weight_decay: 0.0001
  eps: 1e-7
  betas: [0.95, 0.99]

pipeline:
  full_seq: False

corrupted_data_protocol: False

early_stopping:
  monitor: val/acc
  mode: maximize
  patience: 60

head_transformer:
  d_model: 32
  num_layers: 1
  dim_feedforward: 256
  nhead: 1
  dropout: 0.0

aug:
  merge_alphas: [0.5, 0.5]  # 1 / num_modalities
  check_interval: 10
  threshold: 0.07023563717049577
  confidence_coeff: 1.0
  lambda_smooth: 0.5
