modelname: coupled_ssm

optimizer:
  name: schedulefree_adamw
  lr: 1e-4
  warmup_steps: 100
  weight_decay: 0.0
  eps: 1e-7
  betas: [0.95, 0.99]

pipeline:
  full_seq: True

head_transformer:
  d_model: 64
  num_layers: 2
  d_state: 64
  d_conv: 16
  expand: 1