modelname: coupled_ssm

optimizer:
  name: schedulefree_adamw
  lr: 1e-4
  warmup_steps: 100
  weight_decay: 0.0
  eps: 1e-7
  betas: [0.95, 0.99]

pipeline:
  full_seq: True

head_transformer:
  d_model: 128
  num_layers: 8
  d_state: 16
  d_conv: 4
  expand: 2