_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.9.16
        session_history: code/_session_history.ipynb
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 55
                - 103
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.16
            "5": 0.18.6
            "8":
                - 1
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 256
dataset:
    value: mimic_symile
max_epochs:
    value: 20
missing:
    value: '{''train'': [0.0, 0.0], ''valid'': [0.0, 0.0], ''test'': [0.0, 0.0]}'
modelname:
    value: '{''modelname'': ''transformer'', ''optimizer'': {''lr'': 3e-05, ''warmup_steps'': 5, ''weight_decay'': 0.0, ''eps'': 1e-07, ''betas'': [0.95, 0.99]}, ''head_transformer'': {''d_model'': 512, ''num_layers'': 2, ''dim_feedforward'': 128, ''nhead'': 4, ''dropout'': 0.0}}'
precision:
    value: bf16-mixed
seed:
    value: 420
wandb:
    value: '{''project'': ''simple_mml_baseline'', ''group'': ''None''}'
